import random

vowels = ['අ', 'ආ', 'ඇ', 'ඈ', 'ඉ', 'ඊ', 'උ', 'ඌ', 'එ', 'ඒ', 'ඓ', 'ඔ', 'ඕ', 'ඖ']

consonants = {
    'ක':'ක්',
    'ග':'ග්',
    'ජ':'ජ්',
    'ට':'ට්',
    'ද':'ද්',
    'ණ':'ණ්',
    'ත':'ත්',
    'ඩ':'ඩ්',
    'න':'න්',
    'ප':'ප්',
    'බ':'බ්',
    'ම':'ම්',
    'ය':'ය්',
    'ර':'ර්',
    'ල':'ල්',
    'ව':'ව්',
    'ස':'ස්',
    'හ':'හ්',
    'ළ':'ළ්',
    'ං':'ං',
    'ඟ':'ඟ්',
    'ඬ':'ඬ්',
    'ඳ':'ඳ්',
    'ඔ':'ඕ',
    'ඛ':'ඛ්',
    'ඝ':'ඝ්',
    'ඪ්':'ඪ්',
    'ඵ':'ඵ්',
    'ධ':'ධ්',
    'ඨ':'ඨ්',
    'ච':'ච්',
    'ඡ':'ඡ්',
    'ෆ':'ෆ',
    'භ':'භ',
    'ථ':'ථ්',
    'ශ':'ශ්',
    'ෂ':'ෂ්'
}

pili = {
    'ා': 'ආ',
    'ැ': 'ඇ',
    'ෑ': 'ඈ',
    'ි': 'ඉ',
    'ී': 'ඊ',
    'ු': 'උ',
    'ූ': 'ඌ',
    'ෙ': 'එ',
    'ේ': 'ඒ',
    'ෛ': 'ඓ',
    'ො': 'ඔ',
    'ෝ': 'ඕ',
    'ෞ': 'ඖ'
}


word_sign_dict = {

    # Greetings
    'ආයුබෝවන්': 'Sign/01Greetings/welcome.png',
    'ඔබට කොහොමද': 'Sign/01Greetings/how_are_you.png',
    'සුභ උදෑසනක්': 'Sign/01Greetings/good_morning.png',
    'සුභ දවාලක්': 'Sign/01Greetings/good_afternoon.png',
    'සුභ දහවලක්': 'Sign/01Greetings/good_afternoon.png',
    'සුභ සැන්දෑවක්': 'Sign/01Greetings/good_evening.png',
    'සුබ සැන්දෑවක්': 'Sign/01Greetings/good_evening.png',
    'සුභ රාත්\u200dරියක්': 'Sign/01Greetings/good_night.png',
    'සුබ රාත්\u200dරියක්': 'Sign/01Greetings/good_night.png',
    'හමුවීම සතුටක්': 'Sign/01Greetings/nice_to_meet_you.png',
    'මම ඔබට ආදරෙයි': 'Sign/01Greetings/i_love_you.png',
    'නම': 'Sign/01Greetings/name.png',
    'සංඥාවෙන් නම': 'Sign/01Greetings/sign_name.png',
    'සංඛ්\u200dයාවෙන්': 'Sign/01Greetings/sign_name.png',
    'ස්තූතියි': 'Sign/01Greetings/thank_you.png',
    'සමාවෙන්න': 'Sign/01Greetings/sorry.png',
    'දන්නවා': 'Sign/01Greetings/understand.png',
    'දන්නේ නැහැ': 'Sign/01Greetings/dont_understand.png',
    'ඔබගේ නම ද': 'Sign/01Greetings/what_is_your_name.png',
    'ඔබගේ සංඥා නාමය ද': 'Sign/01Greetings/what_is_your_sign_name.png',

    # Actions
    'අහනවා': 'Sign/Actions/ask.png',
    'අහමු': 'Sign/Actions/ask.png',
    'පුළුවන්': 'Sign/Actions/can.png',
    'බැහැ': 'Sign/Actions/cannot.png',
    'මාරු කරනවා': 'Sign/Actions/change.png',
    'මාරු කරමු': 'Sign/Actions/change.png',
    'එනවා': 'Sign/Actions/come.png',
    'එමු': 'Sign/Actions/come.png',
    # 'නැහැ': "Sign/Actions/don't have.png",
    'අකැමති': "Sign/Actions/don't like.png",
    'කනවා': 'Sign/Actions/eat.png',
    'කමු': 'Sign/Actions/eat.png',
    # 'ඉවර': 'Sign/Actions/finish.png',
    'ඉවර කරනවා': 'Sign/Actions/finish.png',
    'ඉවර කරමු': 'Sign/Actions/finish.png',
    'අමතක වෙනවා': 'Sign/Actions/forget.png',
    'යනවා': 'Sign/Actions/go.png',
    'යමු': 'Sign/Actions/go.png',
    'තියනවා': 'Sign/Actions/have.png',
    'උදව් කරනවා': 'Sign/Actions/help.png',
    'උදව් කරමු': 'Sign/Actions/help.png',
    'ඉගෙන ගන්නවා': 'Sign/Actions/learn.png',
    'ඉගෙන ගමු': 'Sign/Actions/learn.png',
    'කැමති': 'Sign/Actions/like.png',
    'බලනවා': 'Sign/Actions/look.png',
    'බලමු': 'Sign/Actions/look.png',
    'ආදරය': 'Sign/Actions/love.png',
    'ආදරය කරනවා': 'Sign/Actions/love.png',
    'ආදරය කරමු': 'Sign/Actions/love.png',
    'හදනවා': 'Sign/Actions/make.png',
    'හදමු': 'Sign/Actions/make.png',
    'සෙල්ලම් කරනවා': 'Sign/Actions/play.png',
    'සෙල්ලම් කරමු': 'Sign/Actions/play.png',
    'විවේක': 'Sign/Actions/rest.png',
    'විවේක ගන්නවා': 'Sign/Actions/rest.png',
    'විවේක ගමු': 'Sign/Actions/rest.png',
    'වාඩි වෙනවා': 'Sign/Actions/sit.png',
    'වාඩි වෙමු': 'Sign/Actions/sit.png',
    'කතා කරනවා': 'Sign/Actions/talk.png',
    'කතා කරමු': 'Sign/Actions/talk.png',
    'මට උගන්වන්න': 'Sign/Actions/teach me.png',
    'උගන්වනවා': 'Sign/Actions/teach.png',
    'උගන්වමු': 'Sign/Actions/teach.png',
    'හිතනවා': 'Sign/Actions/think.png',
    'හිතමු': 'Sign/Actions/think.png',
    'වැඩ': 'Sign/Actions/work.png',

    # Animal
    'සත්තු': 'Sign/animals/animal.png',
    'පූසා': 'Sign/animals/cat.png',
    'කුකුළා': 'Sign/animals/chicken.png',
    'හරකා': 'Sign/animals/cow.png',
    'බල්ලා': 'Sign/animals/dog.png',
    'අලියා': 'Sign/animals/elephant.png',
    'මාලුවා': 'Sign/animals/fish.png',
    'එළුවා': 'Sign/animals/goat.png',
    'සිංහයා': 'Sign/animals/lion.png',
    'වඳුරා': 'Sign/animals/monkey.png',
    'ඌරා': 'Sign/animals/pig.png',
    'මීයා': 'Sign/animals/rat.png',
    'නයා': 'Sign/animals/snake.png',
    'කැස්බෑවා': 'Sign/animals/turtle.png',

    # Asking Questions
    'කීයද': 'Sign/Asking Questions/how many.png',
    'කොහොමද': 'Sign/Asking Questions/how.png',
    'වෙලාව කීයද': 'Sign/Asking Questions/what time.png',
    'මොකක්ද': 'Sign/Asking Questions/what.png',
    'කවදාද': 'Sign/Asking Questions/when.png',
    'කොහේද': 'Sign/Asking Questions/where.png',
    'කවුද': 'Sign/Asking Questions/who.png',
    'ඇයි': 'Sign/Asking Questions/why.png',

    # basic communication
    'සියලුම දෙනා': 'Sign/basic communication/all.png',
    'නරක': 'Sign/basic communication/bad.png',
    'ලස්සන': 'Sign/basic communication/beautiful.png',
    'පිරිසිදු': 'Sign/basic communication/clean.png',
    'බිහිරි': 'Sign/basic communication/Deaf.png',
    'වෙනස්': 'Sign/basic communication/different.png',
    'අපිරිසිදු': 'Sign/basic communication/Dirty.png',
    'ලේසි': 'Sign/basic communication/easy.png',
    'වේගයෙන්': 'Sign/basic communication/fast.png',
    'ටිකක්': 'Sign/basic communication/few.png',
    'හොඳයි': 'Sign/basic communication/good.png',
    'අමාරු': 'Sign/basic communication/hard.png',
    'සාමාන්‍ය අය': 'Sign/basic communication/hearing.png',
    'බොරු': 'Sign/basic communication/lie.png',
    'ගොඩක්': 'Sign/basic communication/many.png',
    'සමහරවිට': 'Sign/basic communication/maybe.png',
    'මම': 'Sign/basic communication/me.png',
    'මුදල්': 'Sign/basic communication/money.png',
    'අලුත්': 'Sign/basic communication/new.png',
    'නැහැ': 'Sign/basic communication/no.png',
    'වයසයි': 'Sign/basic communication/old.png',
    'සමාන': 'Sign/basic communication/same.png',
    'සංඥා භාෂාව': 'Sign/basic communication/sign language.png',
    'හෙමින්': 'Sign/basic communication/slow.png',
    'පරිවර්ථනය': 'Sign/basic communication/translator.png',
    'ඇත්ත': 'Sign/basic communication/truth.png',
    'කැත': 'Sign/basic communication/ugly.png',
    'ඔව්': 'Sign/basic communication/yes.png',
    'ඔබ': 'Sign/basic communication/you.png',

    # clothing
    'තනපට': 'Sign/clothing/bra.png',
    'ගවුම': 'Sign/clothing/frock.png',
    'සාරිය': 'Sign/clothing/saree.png',
    'සරම': 'Sign/clothing/sarong.png',
    'කමිසය': 'Sign/clothing/shirt.png',
    'සපත්තු': 'Sign/clothing/shoes.png',
    'කොට කලිසම': 'Sign/clothing/shorts.png',
    'සෙරෙප්පු': 'Sign/clothing/slippers.png',
    'මේස්': 'Sign/clothing/socks.png',
    'කලීසම': 'Sign/clothing/trousers.png',
    'යට ඇඳුම්': 'Sign/clothing/underwear.png',
    'බැනියම': 'Sign/clothing/vest.png',

    # colors
    'කළු': 'Sign/colors/black.png',
    'නිල්': 'Sign/colors/blue.png',
    'දුඹුරු': 'Sign/colors/brown.png',
    'පාට': 'Sign/colors/colour.png',
    'කොළ': 'Sign/colors/green.png',
    'තැඹිලි': 'Sign/colors/orange.png',
    'දම්': 'Sign/colors/purple.png',
    'රතු': 'Sign/colors/red.png',
    'සුදු': 'Sign/colors/white.png',
    'කහ': 'Sign/colors/yellow.png',

    # family people
    'බබා': 'Sign/family people/baby.png',
    'උපන්දිනය': 'Sign/family people/birthday.png',
    'ළමයා': 'Sign/family people/child.png',
    'ළමයි': 'Sign/family people/children.png',
    'දුව': 'Sign/family people/daughter.png',
    'තාත්තා': 'Sign/family people/father.png',
    'යාළුවා': 'Sign/family people/friend.png',
    'සීයා': 'Sign/family people/grandfather.png',
    'ආච්චී': 'Sign/family people/grandmother.png',
    'සැමියා': 'Sign/family people/husband or wife.png',
    'බිරිඳ': 'Sign/family people/husband or wife.png',
    'පිරිමි': 'Sign/family people/man.png',
    'විවාහක': 'Sign/family people/marry.png',
    'අම්මා': 'Sign/family people/mother.png',
    'අයියා': 'Sign/family people/older brother.png',
    'අක්කා': 'Sign/family people/older sister.png',
    'මිනිස්සු': 'Sign/family people/people.png',
    'පුද්ගලයා': 'Sign/family people/person.png',
    'පුතා': 'Sign/family people/son.png',
    'ගැහැණු': 'Sign/family people/woman.png',
    'මල්ලී': 'Sign/family people/younger brother.png',
    'නංගී': 'Sign/family people/younger sister.png',

    # feelings
    'තරහ': 'Sign/feelings/angry.png',
    'පාලු': 'Sign/feelings/bored.png',
    'සන්සුන්': 'Sign/feelings/calm.png',
    'නපුරු': 'Sign/feelings/evil.png',
    'සතුටු': 'Sign/feelings/happy.png',
    'සිනාව': 'Sign/feelings/laughing.png',
    'කම්මැලි': 'Sign/feelings/lazy.png',
    'දුක': 'Sign/feelings/sad.png',
    'බය': 'Sign/feelings/scared.png',
    'නිදිමත': 'Sign/feelings/sleepy.png',
    'පුදුම': 'Sign/feelings/suprised.png',
    'මහන්සි': 'Sign/feelings/tired.png',

    # food drink
    'ඇපල්': 'Sign/FoodDrink/apple.png',
    'කෙසෙල්': 'Sign/FoodDrink/banana.png',
    'බෝංචි': 'Sign/FoodDrink/bean.png',
    'පාන්': 'Sign/FoodDrink/bread.png',
    'උදේ ආහාරය': 'Sign/FoodDrink/breakfast.png',
    'වම්බටු': 'Sign/FoodDrink/brinjal.png',
    'බනිස්': 'Sign/FoodDrink/bun.png',
    'කේක්': 'Sign/FoodDrink/cake.png',
    'විස්කෝතු': 'Sign/FoodDrink/cake.png',
    'කුකුල්මස්': 'Sign/FoodDrink/chicken.png',
    'දෙහි': 'Sign/FoodDrink/citrus.png',
    'පොල්': 'Sign/FoodDrink/coconut.png',
    'උයනවා': 'Sign/FoodDrink/cook.png',
    'කෝප්පය': 'Sign/FoodDrink/cup.png',
    'මීකිරි': 'Sign/FoodDrink/curd.png',
    'රාත්‍රී ආහාරය': 'Sign/FoodDrink/dinner.png',
    'බිත්තර': 'Sign/FoodDrink/egg.png',
    'මාලු': 'Sign/FoodDrink/fish.png',
    'ආහාර': 'Sign/FoodDrink/food.png',
    'පළතුරු': 'Sign/FoodDrink/fruit.png',
    'පිරුණු': 'Sign/FoodDrink/full.png',
    'ආප්ප': 'Sign/FoodDrink/hoppers.png',
    'බඩගිනි': 'Sign/FoodDrink/hungry.png',
    'ice cream': 'Sign/FoodDrink/ice cream.png',
    'වරකා': 'Sign/FoodDrink/jackfruit.png',
    'පිහිය': 'Sign/FoodDrink/knife.png',
    'දිවා ආහාරය': 'Sign/FoodDrink/lunch.png',
    'අඹ': 'Sign/FoodDrink/mango.png',
    'කිරි': 'Sign/FoodDrink/milk.png',
    'ගස්ලබු': 'Sign/FoodDrink/papaw.png',
    'අන්නාසි': 'Sign/FoodDrink/pineapple.png',
    'පිඟාන': 'Sign/FoodDrink/plate.png',
    'අල': 'Sign/FoodDrink/potato.png',
    'බත්': 'Sign/FoodDrink/rice and curry.png',
    'සෝඩා': 'Sign/FoodDrink/soda.png',
    'කුළුබඩු යෙදු': 'Sign/FoodDrink/spicy.png',
    'හැන්ද': 'Sign/FoodDrink/spoon.png',
    'තේ': 'Sign/FoodDrink/tea.png',
    'එළවළු': 'Sign/FoodDrink/vegetable.png',
    'වතුර': 'Sign/FoodDrink/water.png',

    # numbers
    '0': 'Sign/numbers/0.jpeg',
    'බින්දුව': 'Sign/numbers/0.jpeg',
    'එක': 'Sign/numbers/1.png',
    '1': 'Sign/numbers/1.png',
    '10': 'Sign/numbers/10.png',
    'දහය': 'Sign/numbers/10.png',
    'සීය': 'Sign/numbers/100.png',
    '100': 'Sign/numbers/100.png',
    'දහස': 'Sign/numbers/1000.png',
    '1000': 'Sign/numbers/1000.png',
    'ලක්ෂය': 'Sign/numbers/100000.png',
    'සියක් දහස': 'Sign/numbers/100000.png',
    '100000': 'Sign/numbers/100000.png',
    'එකොළහ': 'Sign/numbers/11.png',
    '11': 'Sign/numbers/11.png',
    'දොළහ': 'Sign/numbers/12.png',
    '12': 'Sign/numbers/12.png',
    'දහතුන': 'Sign/numbers/13.png',
    '13': 'Sign/numbers/13.png',
    'දාහතර': 'Sign/numbers/14.png',
    '14': 'Sign/numbers/14.png',
    'පහළොව': 'Sign/numbers/15.png',
    '15': 'Sign/numbers/15.png',
    'දාසය': 'Sign/numbers/16.png',
    '16': 'Sign/numbers/16.png',
    'දාහත': 'Sign/numbers/17.png',
    '17': 'Sign/numbers/17.png',
    'දහඅට': 'Sign/numbers/18.png',
    '18': 'Sign/numbers/18.png',
    'දහනමය': 'Sign/numbers/19.png',
    '19': 'Sign/numbers/19.png',
    'දෙක': 'Sign/numbers/2.png',
    '2': 'Sign/numbers/2.png',
    'විස්ස': 'Sign/numbers/20.png',
    '20': 'Sign/numbers/20.png',
    'දෙසීය': 'Sign/numbers/200.png',
    '200': 'Sign/numbers/200.png',
    'තුන': 'Sign/numbers/3.png',
    '3': 'Sign/numbers/3.png',
    'තිහ': 'Sign/numbers/30.png',
    '30': 'Sign/numbers/30.png',
    'තින්සීය': 'Sign/numbers/300.png',
    '300': 'Sign/numbers/300.png',
    'හතර': 'Sign/numbers/4.png',
    '4': 'Sign/numbers/4.png',
    'හතලිහ': 'Sign/numbers/40.png',
    '40': 'Sign/numbers/40.png',
    'හාරසීය': 'Sign/numbers/400.png',
    '400': 'Sign/numbers/400.png',
    'පහ': 'Sign/numbers/5.png',
    '5': 'Sign/numbers/5.png',
    'පනහ': 'Sign/numbers/50.png',
    '50': 'Sign/numbers/50.png',
    'පන්සීය': 'Sign/numbers/500.png',
    '500': 'Sign/numbers/500.png',
    'හය': 'Sign/numbers/6.png',
    '6': 'Sign/numbers/6.png',
    'හැට': 'Sign/numbers/60.png',
    '60': 'Sign/numbers/60.png',
    'හයසීය': 'Sign/numbers/600.png',
    '600': 'Sign/numbers/600.png',
    'හත': 'Sign/numbers/7.png',
    '7': 'Sign/numbers/7.png',
    'හැත්තාව': 'Sign/numbers/70.png',
    '70': 'Sign/numbers/70.png',
    'හත්සීය': 'Sign/numbers/700.png',
    '700': 'Sign/numbers/700.png',
    'අට': 'Sign/numbers/8.png',
    '8': 'Sign/numbers/8.png',
    'අසූව': 'Sign/numbers/80.png',
    '80': 'Sign/numbers/80.png',
    'අටසීය': 'Sign/numbers/800.png',
    '800': 'Sign/numbers/800.png',
    'නවය': 'Sign/numbers/9.png',
    '9': 'Sign/numbers/9.png',
    'අනූව': 'Sign/numbers/90.png',
    '90': 'Sign/numbers/90.png',
    'නවසීය': 'Sign/numbers/900.png',
    '900': 'Sign/numbers/900.png',

    # personal health
    'වයස': 'Sign/PersonalHealth/age.png',
    'බාහු වේදනාව': 'Sign/PersonalHealth/armPain.png',
    'කොණ්ඩය පීරනවා': 'Sign/PersonalHealth/brush hair.png',
    'දත් මැදීම': 'Sign/PersonalHealth/brush teeth.png',
    'සිසිල': 'Sign/PersonalHealth/cold.png',
    'මරණය': 'Sign/PersonalHealth/die.png',
    'දොස්තර': 'Sign/PersonalHealth/doctor.png',
    'කොණ්ඩය කැපීම': 'Sign/PersonalHealth/haircut.png',
    'හිසරදය': 'Sign/PersonalHealth/headache.png',
    'නීරෝගී': 'Sign/PersonalHealth/healthy.png',
    'උණුසුම': 'Sign/PersonalHealth/hot.png',
    'ජිවිතය': 'Sign/PersonalHealth/live.png',
    'බෙහෙත්': 'Sign/PersonalHealth/medicine.png',
    'වේදනාව': 'Sign/PersonalHealth/pain.png',
    'ගර්භණී': 'Sign/PersonalHealth/pregnant.png',
    'රැවුල බානවා': 'Sign/PersonalHealth/shave.png',
    'නානවා': 'Sign/PersonalHealth/shower.png',
    'රෝගී': 'Sign/PersonalHealth/sick.png',
    'නිදාගන්නවා': 'Sign/PersonalHealth/sleep.png',
    'බඩේ කැක්කුම': 'Sign/PersonalHealth/stomachache.png',
    'වැසිකිළිය': 'Sign/PersonalHealth/toilet.png',

    # school
    'කෘෂිකර්මය': 'Sign/school/agriculture.png',
    'උසස් පෙළ': 'Sign/school/al.png',
    'දානය': 'Sign/school/armsgiving.png',
    'චිත්\u200dර': 'Sign/school/art.png',
    'පොත': 'Sign/school/book.png',
    'බෑගය': 'Sign/school/bookbag.png', # not working
    'පාසල': 'Sign/school/college.png',
    'නැටුම්': 'Sign/school/dance.png',
    'desk': 'Sign/school/desk.png',
    'ඉංග්\u200dරීසි': 'Sign/school/english.png',
    'පාසල හැර ගිය': 'Sign/school/leave school.png',
    'ගණිත': 'Sign/school/maths.png',
    'පාලක': 'Sign/school/matron.png',
    'පාලිකාව': 'Sign/school/matron.png',
    'සාමාන්\u200dය පෙළ': 'Sign/school/ol.png',
    'කොල': 'Sign/school/paper.png',
    'පෑන': 'Sign/school/pen.png',
    'පැන්සල්': 'Sign/school/pencil.png',
    'විදුහල්පති': 'Sign/school/principle.png',
    'විද්\u200dයාව': 'Sign/school/science.png',
    'පාඩම් කරනවා': 'Sign/school/study.png',
    'ගුරුවරයා': 'Sign/school/teacher.png',
    'ගුරුතුමා': 'Sign/school/teacher.png',
    'පරීක්ෂණය': 'Sign/school/test.png',
    'පෙළ පොත': 'Sign/school/textbook.png', #
    'විශ්වවිද්\u200dයාලය': 'Sign/school/university.png',
    '1 ශ්\u200dරේණි': 'Sign/school/year1.png',
    '10 ශ්\u200dරේණි': 'Sign/school/year10.png',
    '11 ශ්\u200dරේණි': 'Sign/school/year11.png',
    '2 ශ්\u200dරේණි': 'Sign/school/year2.png',
    '3 ශ්\u200dරේණි': 'Sign/school/year3.png',
    '4 ශ්\u200dරේණි': 'Sign/school/year4.png',
    '5 ශ්\u200dරේණි': 'Sign/school/year5.png',
    '6 ශ්\u200dරේණි': 'Sign/school/year6.png',
    '7 ශ්\u200dරේණි': 'Sign/school/year7.png',
    '8 ශ්\u200dරේණි': 'Sign/school/year8.png',
    '9 ශ්\u200dරේණි': 'Sign/school/year9.png',

    # SportsCreations
    'කැරම්': 'Sign/SportsCreations/carrom.png',
    'cricket': 'Sign/SportsCreations/cricket.png',
    # '': 'Sign/SportsCreations/dance.png',
    'ඩීවීඩී': 'Sign/SportsCreations/dvd.png',
    'vcd': 'Sign/SportsCreations/dvd.png',
    'cd': 'Sign/SportsCreations/dvd.png',
    'පාපන්දු': 'Sign/SportsCreations/football.png',
    'තරග': 'Sign/SportsCreations/match.png',
    'පුහුණු': 'Sign/SportsCreations/practice.png',
    'දුවනවා': 'Sign/SportsCreations/running.png',
    'ක්\u200dරීඩා': 'Sign/SportsCreations/sports.png',
    'පීනනවා': 'Sign/SportsCreations/swimming.png',
    'ටීවී': 'Sign/SportsCreations/tv.png',
    'වොලිබෝල්': 'Sign/SportsCreations/volleyball.png',
    'දිනනවා': 'Sign/SportsCreations/win.png',

    # SriLankaWorld
    'ශ්\u200dරී පාදය': "Sign/SriLankaWorld/Adam's peak.png",
    'අකුරැස්ස': 'Sign/SriLankaWorld/akuressa.png',
    'අනුරාධපුරය': 'Sign/SriLankaWorld/anuradhapura.png',
    'අරාබිය': 'Sign/SriLankaWorld/arabia.png',
    'බුද්ධාගම': 'Sign/SriLankaWorld/buddhism.png',
    'චීනය': 'Sign/SriLankaWorld/china.png',
    'ක්\u200dරිස්තියානි': 'Sign/SriLankaWorld/christian.png',
    'කොළඹ': 'Sign/SriLankaWorld/colombo.png',
    'එංගලන්තේ': 'Sign/SriLankaWorld/England.png',
    'ආගන්තුකයා': 'Sign/SriLankaWorld/foreigner.png',
    'ගාල්ල': 'Sign/SriLankaWorld/galle.png',
    'රජය': 'Sign/SriLankaWorld/governmet.png',
    'හින්දු': 'Sign/SriLankaWorld/hindu.png',
    'ඉන්දියාව': 'Sign/SriLankaWorld/india.png',
    'යාපනය': 'Sign/SriLankaWorld/jaffna.png',
    'ජපානය': 'Sign/SriLankaWorld/japan.png',
    'මහනුවර': 'Sign/SriLankaWorld/kandy.png',
    'කතරගම': 'Sign/SriLankaWorld/kataragama.png',
    'එල්ටීටීඊ': 'Sign/SriLankaWorld/LTTE.png',
    'මාතර': 'Sign/SriLankaWorld/matara.png',
    'මුස්ලිම්': 'Sign/SriLankaWorld/muslim.png',
    'නුවරඑළිය': 'Sign/SriLankaWorld/nuwara eliya.png',
    'පොළොන්නරුව': 'Sign/SriLankaWorld/polonnaruwa.png',
    'සිංහල': 'Sign/SriLankaWorld/sinhala.png',
    'ශ්\u200dරී ලංකාව': 'Sign/SriLankaWorld/Sri Lanka.png',
    'දෙමළ': 'Sign/SriLankaWorld/tamil.png',
    'පන්සල': 'Sign/SriLankaWorld/temple.png',
    'ත්\u200dරිකුණාමලය': 'Sign/SriLankaWorld/trincomalee.png',
    'ඇමෙරිකාව': 'Sign/SriLankaWorld/USA.png',
    'ගම': 'Sign/SriLankaWorld/village.png',

    # TimeDate
    'අප්\u200dරේල්': 'Sign/TimeDate/april.png',
    'අගෝස්තු': 'Sign/TimeDate/august.png',
    'දවස': 'Sign/TimeDate/day.png',
    'දෙසැම්බර්': 'Sign/TimeDate/december.png',
    'හැමදාම': 'Sign/TimeDate/everyday.png',
    'පෙබරවාරි': 'Sign/TimeDate/february.png',
    'සිකුරාදා': 'Sign/TimeDate/friday.png',
    'හමාර': 'Sign/TimeDate/half-past.png',
    'බාගෙන්': 'Sign/TimeDate/half-past.png',
    'නිවාඩු': 'Sign/TimeDate/holiday.png',
    'ජනවාරි': 'Sign/TimeDate/january.png',
    'ජුලි': 'Sign/TimeDate/july.png',
    'ජුනි': 'Sign/TimeDate/june.png',
    'මාර්තු': 'Sign/TimeDate/march.png',
    'මැයි': 'Sign/TimeDate/may.png',
    'සඳුදා': 'Sign/TimeDate/monday.png',
    'මාසය': 'Sign/TimeDate/month.png',
    'නොවැම්බර්': 'Sign/TimeDate/november.png',
    '0 0': 'Sign/TimeDate/o-clock.png',
    'ඔක්තෝම්බර්': 'Sign/TimeDate/october.png',
    'පෝය': 'Sign/TimeDate/poya.png',
    'සෙනසුරාදා': 'Sign/TimeDate/saturday.png',
    'සැප්තැම්බර්': 'Sign/TimeDate/september.png',
    'අවුරුදු': 'Sign/TimeDate/sinhala and tamil new year.png',
    'ඉරිදා': 'Sign/TimeDate/sunday.png',
    'බ්\u200dරහස්පතින්දා': 'Sign/TimeDate/thursday.png',
    'අද': 'Sign/TimeDate/today.png',
    'හෙට': 'Sign/TimeDate/tomorrow.png',
    'අඟහරුවාදා': 'Sign/TimeDate/tuesday.png',
    'බදාදා': 'Sign/TimeDate/wednesday.png',
    'සතිය': 'Sign/TimeDate/week.png',
    'වෙසක්': 'Sign/TimeDate/wesak.png',
    'අවුරුද්ද': 'Sign/TimeDate/year.png',
    'ඊයේ': 'Sign/TimeDate/yesterday.png',

    # TrasportationPlaces
    'අහස්යානය': 'Sign/TrasportationPlaces/airplane.png',
    'හමුදාව': 'Sign/TrasportationPlaces/army.png',
    'බැංකුව': 'Sign/TrasportationPlaces/bank.png',
    'බයිසිකලය': 'Sign/TrasportationPlaces/bicycle.png',
    'බෝට්ටුව': 'Sign/TrasportationPlaces/boat.png',
    'බසය': 'Sign/TrasportationPlaces/bus.png',
    'කාරය': 'Sign/TrasportationPlaces/car.png',
    'හෝටලය': 'Sign/TrasportationPlaces/hotel.png',
    'ගෙදර': 'Sign/TrasportationPlaces/house.png',
    'මෝටර් සයිකලය': 'Sign/TrasportationPlaces/motorbike.png',
    'පොලිසිය': 'Sign/TrasportationPlaces/police.png',
    'තැපැල් කන්තෝරුව': 'Sign/TrasportationPlaces/post office.png',
    'සාප්පුව': 'Sign/TrasportationPlaces/shop.png',
    'ත්\u200dරීවීලරය': 'Sign/TrasportationPlaces/three wheeler.png',
    'කෝච්චිය': 'Sign/TrasportationPlaces/train.png',
    'වෑන්': 'Sign/TrasportationPlaces/van.png',
    'ඇවිදිනවා': 'Sign/TrasportationPlaces/walk.png',

    # weathernature
    'මල': 'Sign/weathernature/flower.png',
    'තණකොළ': 'Sign/weathernature/grass.png',
    # 'කොල': 'Sign/weathernature/leaf.png',
    'මුහුද': 'Sign/weathernature/ocean.png',
    'වැස්ස': 'Sign/weathernature/rain.png',
    'ගල': 'Sign/weathernature/rock.png',
    'වැලි': 'Sign/weathernature/sand.png',
    'ඉර': 'Sign/weathernature/sun.png',
    'ගස': 'Sign/weathernature/tree.png'
}

letter_sign_dict = {
    'අ': 'Sign/alphabets/letter1.png',
    'ආ': 'Sign/alphabets/letter2.png',
    'ඇ': 'Sign/alphabets/letter3.png',
    'ඈ': 'Sign/alphabets/letter4.png',
    'ඉ': 'Sign/alphabets/letter5.png',
    'ඊ': 'Sign/alphabets/letter6.png',
    'උ': 'Sign/alphabets/letter7.png',
    'ඌ': 'Sign/alphabets/letter8.png',
    'එ': 'Sign/alphabets/letter9.png',
    'ඒ': 'Sign/alphabets/letter10.png',
    'ඔ': 'Sign/alphabets/letter11.png',
    'ඕ': 'Sign/alphabets/letter12.png',
    'ඖ': 'Sign/alphabets/letter51.png',
    'ක්': 'Sign/alphabets/letter13.png',
    'ග්': 'Sign/alphabets/letter14.png',
    'ජ්': 'Sign/alphabets/letter15.png',
    'ට්': 'Sign/alphabets/letter16.png',
    'ද්': 'Sign/alphabets/letter17.png',
    'ණ්': 'Sign/alphabets/letter18.png',
    'ත්': 'Sign/alphabets/letter19.png',
    'ඩ්': 'Sign/alphabets/letter20.png',
    'න්': 'Sign/alphabets/letter21.png',
    'ප්': 'Sign/alphabets/letter22.png',
    'බ්': 'Sign/alphabets/letter23.png',
    'ම්': 'Sign/alphabets/letter24.png',
    'ය්': 'Sign/alphabets/letter25.png',
    'ර්': 'Sign/alphabets/letter26.png',
    'ල්': 'Sign/alphabets/letter27.png',
    'ව්': 'Sign/alphabets/letter28.png',
    'ස්': 'Sign/alphabets/letter29.png',
    'හ්': 'Sign/alphabets/letter30.png',
    'ළ්': 'Sign/alphabets/letter31.png',
    'ං': 'Sign/alphabets/letter32.png',
    'ඟ්': 'Sign/alphabets/letter33.png',
    'ඬ්': 'Sign/alphabets/letter34.png',
    'ඳ්': 'Sign/alphabets/letter35.png',
    'ඹ්': 'Sign/alphabets/letter36.png',
    'ඛ්': 'Sign/alphabets/letter37.png',
    'ඝ්': 'Sign/alphabets/letter38.png',
    'ඪ්': 'Sign/alphabets/letter39.png',
    'ඵ්': 'Sign/alphabets/letter40.png',
    'ධ්': 'Sign/alphabets/letter41.png',
    'ඨ්': 'Sign/alphabets/letter42.png',
    'ච්': 'Sign/alphabets/letter43.png',
    'ඡ්': 'Sign/alphabets/letter44.png',
    # 'ය්': 'Sign/alphabets/letter45.png',
    'ෆ': 'Sign/alphabets/letter46.png',
    'භ': 'Sign/alphabets/letter47.png',
    'ථ්': 'Sign/alphabets/letter48.png',
    'ඓ': 'Sign/alphabets/letter49.png',
    'ඍ': 'Sign/alphabets/letter50.png',
    '': 'Sign/alphabets/letter51.png',
    # 'ර්': 'Sign/alphabets/letter53.png',
    '(': 'Sign/alphabets/letter54.png',
    'ශ්': 'Sign/alphabets/letter55.png',
    'ෂ්': 'Sign/alphabets/letter56.png',



    # numbers

    '0': 'Sign/numbers/0.jpeg',
    '1': 'Sign/numbers/1.png',
    '2': 'Sign/numbers/2.png',
    '3': 'Sign/numbers/3.png',
    '4': 'Sign/numbers/4.png',
    '5': 'Sign/numbers/5.png',
    '6': 'Sign/numbers/6.png',
    '7': 'Sign/numbers/7.png',
    '8': 'Sign/numbers/8.png',
    '9': 'Sign/numbers/9.png',

}

keys = list(word_sign_dict.keys())
random.shuffle(keys)
full_key = ' '.join(keys)